name: basic
on: [pull]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # verifies the number of passing tests
          # and passes a variable to Cypress
          # to be read using Cypress.env("lastName")
          command: npm run test:e2e
